### ISSUE TITLE
Deployed mox/jira-software on aws eks, cannot make https to work

### ISSUE THREAD

**Issue by byang0818** [javimox/helm-charts#20]
Deployed from following command:

Helm install jira --service.type="LoadBalancer" mox/jira-software -n jira

http connection works fine, but cannot make https to work, I have cert attached to the loadbalacer.

Here is the service looks like:

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: jira
    meta.helm.sh/release-namespace: jira
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-xxxx-1:xxxxxxxxxxxx:certificate/b185f056-47d9-4ad6-ba0a-xxxxxxxxxxxx
  creationTimestamp: "2020-08-06T15:07:52Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jira-software
    app.kubernetes.io/version: 8.11.0
    helm.sh/chart: jira-software-0.3.2
  name: jira-jira-software
  namespace: jira
  resourceVersion: "15170416"
  selfLink: /api/v1/namespaces/jira/services/jira-jira-software
  uid: xxxxxxxxxxxxxx
spec:
  clusterIP: xxx.xx.xxx.xxx
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31482
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/name: jira-software
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: xxxxxxxxxxxxxx.us-xxxx-1.elb.amazonaws.com

**Comment by javimox** [comment]
@byang0818 : thanks for reaching out to me. Can you also tell if there's activity in the catalina logs when you are trying to connect to Jira over https or the connections are just not reaching the container?

@tetsun : may I ask you again if did https work for you?

**Comment by byang0818** [comment]
@javimox, We tried a lot things, and finally made https working.

Basically, we have the followings at value.yml:
service:
  ## For minikube, set this to NodePort, elsewhere use LoadBalancer
  type: LoadBalancer
  ## Use serviceLoadBalancerIP to request a specific static IP, otherwise leave blank
  ##
  ## Avoid removing the http connector, as the Synchrony proxy health check, still requires HTTP
  ## HTTP Port, must be the same as ATL_TOMCAT_PORT (default: 8080)
  port: 8443
  ## HTTPS Port, in case ATL_TOMCAT_SCHEME is set to 'https'
  httpsPort: 8443

 ATL_TOMCAT_PORT: 8443
  ATL_TOMCAT_SCHEME: https
  ATL_TOMCAT_SECURE: true

**Comment by javimox** [comment]
Great! I am going to close this issue then. Thanks for your feedback.
