### ISSUE TITLE
Get password of postgresql from secret

### ISSUE THREAD

**Issue by kmmanto** [javimox/helm-charts#22]
Specifying the password on yaml files will put password in plaintext. At least specify it in a secret.

**Comment by javimox** [comment]
Hi @kmmanto,

thanks for your comment. I wouldn't consider it as an issue, though. PostgreSQL is deployed as subchart using the bitnami flavor, so specifying the passwords using secrets is actually supported.

[bitnami postgresql docs](https://github.com/bitnami/charts/tree/master/bitnami/postgresql):

```
global.postgresql.existingSecret:
Name of existing secret to use for PostgreSQL passwords (overrides existingSecret)

existingSecret:
Name of existing secret to use for PostgreSQL passwords.
The secret has to contain the keys postgresql-postgres-password which is the password for postgresqlUsername
when it is different of postgres, postgresql-password which will override postgresqlPassword,
postgresql-replication-password which will override replication.password and postgresql-ldap-password which will
be sed to authenticate on LDAP. The value is evaluated as a template.
```

**Comment by kmmanto** [comment]
Right.  So specifying `existingSecret` will override the values here?

https://github.com/javimox/helm-charts/blob/master/charts/jira-software/values.yaml#L231

**Comment by javimox** [comment]
my bad. I thought you meant `postgresqlPassword` parameter.

So, you are right. I am going to fix that _soon_, thanks for letting me know.

The only tricky part here is that secrets can't be called from configmaps, which means that the `configmap-db-helper.yaml` used to create the database wouldn't work the way it is working now.

My approach here might be using an env variable to save the jira db password from the secret and then call it from postgres, something like this:

```mysql
\set pw `echo "'$_JIRA_DB_PW'"`
CREATE USER {{ .Values.databaseConnection.user }} WITH ENCRYPTED PASSWORD :pw;
```
It wouldn't be best practice but now I can't think of other way. Ideas are always welcome, so feel free to comment here if you have another approach.

**Comment by javimox** [comment]
Hi,

The issue got closed when I merged to master. If the problem persists on your side, please let me know.
