### ISSUE TITLE
Helm complains about apiVersion which should be v1

### ISSUE THREAD

**Issue by AlbanMontaigu** [javimox/helm-charts#3]
Hello,
Thanks for accepting my pull request  and happy to contribute :).
Unfortunately version 0.2.0 seems to introduce a regression about helm api.
He is now complaing about apiVersion which should be v1... 
After rechecking the code I definitely not see any reason for that changes where minor (and by the way sorry if it  was me who introduced the regression).

My only idea it maybe stupid but contemplating this commit: https://github.com/javimox/helm-charts/commit/8be308c0138dfd1ffd517a412dd361d11b7727a7 I see a lot of changes on every line which seems not the case in reality.

So I might bet that this commit introduced kind of CRLF like issue which generated a strange helm behavior. What do you think ?

Kind Regards

**Comment by AlbanMontaigu** [comment]
Maybe having a gitattributes files could help and renomalizing the repo / commit it again could be enough : https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by javimox** [comment]
I can't reproduce the warning. Could you plese paste the command that you ran and its output?

The changes in https://github.com/javimox/helm-charts/commit/8be308c0138dfd1ffd517a412dd361d11b7727a7 are normal, as every release generates a new entry in the helm repository index.

**Comment by AlbanMontaigu** [comment]
Thanks for your check / feedback.

I didn't use directly helm command.

I'm using rancher v2.4.3, then adding your chart as catalog via "manage catalog -> add" and then launch app.

So the commands are a bit hidden.

But the good news is I might found a solution (even if it does not bring the root cause).

Seems it's could be a rancher catalog / helm repo sync issue.

I tried the following which fixed the issue : remove the rancher catalog entry with its charts and then re add it.

Now I'm able to deploy the charts without warning.

I'll close the issue but I'll monitor more carefully the next chart update.

Sorry for the disturbance ! And thanks again :)

**Comment by javimox** [comment]
Great! Thanks for your feedback.
