### ISSUE TITLE
JIRA Software - Customize postgres init container image

### ISSUE THREAD

**Issue by CtrlAltDft** [javimox/helm-charts#32]
I saw in the deployment template image for 'init-postgres' container is fixed to be 'postgres:9.6.11-alpine'. Can you update it so that it can be changed using values.yml file please

**Comment by javimox** [comment]
Hi @CtrlAltDft ,

sorry it took so long. I have been quite busy.
You can now use the value `initContainerImages.postgres` to specify what init container image you want to use.

Regards,
