### ISSUE TITLE
Meet error when deploy on openshift

### ISSUE THREAD

**Issue by Karl-br** [javimox/helm-charts#5]
helm install demo-01 mox/confluence-server
when i use the command to deploy confluence on Openshift 4.4 i meet CrashLoopBackOff error.
here is the log

INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
INFO:root:/var/atlassian/application-data/confluence/confluence.cfg.xml exists; skipping.
INFO:root:User is currently root. Will downgrade run user to confluence
INFO:root:Running Confluence with command '/bin/su', arguments ['/bin/su', 'confluence', '-c', '/opt/atlassian/confluence/bin/start-confluence.sh -fg']
su: System error

Please tell me how to deal with this problem.
Thank you

**Comment by javimox** [comment]
HI @Karl-br , those helm-charts have been tested in Kubernetes. I can't help in this case.

My suggestion is to look at the security policy in your OpenShift. It is my first guess, as it seems that somehow triggers an error when calling `su`. Apart from that, you can contact Atlassian and ask if their containers have been tested in OpenShift.

Good luck with that and feel free to post any update on this. At the end we might be able to change the Chart to make it also compatible with OpenShift.

**Comment by javimox** [comment]
inactive for 1 week. Closing...
